export interface Pattern {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  sourceBook: string;
  sourceAuthor: string;
  relatedBookSlug: string;
  keySteps: string[];
  useCases: string[];
}

export const patterns: Pattern[] = [
  {
    slug: "value-ladder-automation",
    title: "Value Ladder AI Automation",
    subtitle: "Build a 5-step customer ascension model with AI",
    description:
      "Automate Russell Brunson's Value Ladder framework using AI. Design your product ecosystem from lead magnets to high-ticket offers, with AI-generated content and positioning for each tier. Start by defining your Dream Customer with AI-generated personas, then map a 5-step ascending product ladder where AI identifies gaps and proposes new tiers. Generate Hook-Story-Offer content for each level, build a 7-Phase Funnel from cold to warm to hot traffic, and create a Soap Opera Sequence — a 5-day AI-written trust-building email series that converts subscribers into buyers.",
    sourceBook: "DotCom Secrets",
    sourceAuthor: "Russell Brunson",
    relatedBookSlug: "ai-marketing-architect",
    keySteps: [
      "Define your Dream Customer with AI-generated personas",
      "Map the 5-step Value Ladder — AI identifies gaps and proposes new tiers",
      "Generate Hook-Story-Offer content for each product level",
      "Build the 7-Phase Funnel: Cold to Warm to Hot traffic sequences",
      "Create Soap Opera Sequence: AI writes 5-day trust-building email series",
    ],
    useCases: [
      "Online course creators launching their first product ladder",
      "Coaches scaling from 1-on-1 to group programs",
      "E-commerce businesses adding digital upsells",
    ],
  },
  {
    slug: "mass-movement-design",
    title: "Mass Movement Design with AI",
    subtitle: "Build a brand that leads a movement, not just sells a product",
    description:
      "Apply Russell Brunson's Expert Secrets framework using AI to design a Mass Movement. Define your Charismatic Leader identity, Cause, and New Opportunity to position yourself as a category creator. Craft the Epiphany Bridge — an 8-step storytelling script generated by AI that turns your origin story into a conversion tool. Build a Belief System Architecture around your Big Domino statement and dismantle 3 false beliefs. Then generate a complete Perfect Webinar Script with AI across all 4 parts, and execute a Dream 100 Traffic Strategy to build your engaged audience.",
    sourceBook: "Expert Secrets",
    sourceAuthor: "Russell Brunson",
    relatedBookSlug: "ai-brand-architect",
    keySteps: [
      "Define your Charismatic Leader identity, Cause, and New Opportunity",
      "Craft the Epiphany Bridge: 8-step storytelling script with AI",
      "Build Belief System Architecture: Big Domino + 3 false beliefs",
      "Generate Perfect Webinar Script: complete 4-part AI-written script",
      "Execute Dream 100 Traffic Strategy for audience building",
    ],
    useCases: [
      "Personal brands building an engaged community",
      "Thought leaders launching a new methodology",
      "Consultants positioning as category creators",
    ],
  },
  {
    slug: "dream-100-traffic",
    title: "Dream 100 AI Traffic Strategy",
    subtitle:
      "Find your customers where they already are — with AI",
    description:
      "Implement Russell Brunson's Traffic Secrets Dream 100 strategy using AI. Build complete customer avatars from demographic and behavioral data, then identify 100 places your dream customers already congregate using AI-powered research. Generate Hook-Story-Offer content optimized for each platform, design both organic (Work Your Way In) and paid (Buy Your Way In) strategies, and build a Follow-Up Funnel with AI email sequences that convert cold prospects into paying customers.",
    sourceBook: "Traffic Secrets",
    sourceAuthor: "Russell Brunson",
    relatedBookSlug: "ai-traffic-architect",
    keySteps: [
      "AI-generated Dream Customer Avatar from demographic + behavioral data",
      "Identify 100 places your dream customers congregate with AI research",
      "Generate Hook-Story-Offer content optimized per platform",
      "Design organic (Work Your Way In) and paid (Buy Your Way In) strategies",
      "Build Follow-Up Funnel: AI email sequences for cold-to-buyer conversion",
    ],
    useCases: [
      "SaaS startups seeking product-market fit traffic",
      "Local businesses expanding to online audiences",
      "Content creators diversifying traffic sources",
    ],
  },
  {
    slug: "story-driven-copy",
    title: "Story-Driven AI Copywriting",
    subtitle:
      "Every word wins or loses sales — AI fixes the ones that lose",
    description:
      "Apply Jim Edwards' Copywriting Secrets with AI to transform your words into sales. Use a 5-step Personal Story Mining process to find emotional turning points, then structure them using AI's Hero's Journey Formula — a 7-step narrative arc. Identify which of the 10 Buying Motivators drive your specific audience, generate a Headline Arsenal spanning Curiosity, Benefit, and Problem-Solution categories, and produce platform-specific copy with Hook, Story, Value, and CTA optimized for each channel.",
    sourceBook: "Copywriting Secrets",
    sourceAuthor: "Jim Edwards",
    relatedBookSlug: "ai-story-architect",
    keySteps: [
      "Personal Story Mining: 5-step process for finding emotional turning points",
      "Hero's Journey Formula: 7-step narrative arc designed by AI",
      "10 Buying Motivators: AI identifies which core motivators drive your audience",
      "Headline Arsenal: generate headlines across Curiosity, Benefit, Problem-Solution",
      "Platform-Specific Copy: Hook, Story, Value, CTA for each channel",
    ],
    useCases: [
      "Marketers optimizing landing page conversion rates",
      "Email marketers improving open and click rates",
      "Ad copywriters generating high-performing variations",
    ],
  },
  {
    slug: "product-launch-sequence",
    title: "AI Product Launch Sequence",
    subtitle: "Launch with a proven sequence — not guesswork",
    description:
      "Automate Jeff Walker's Product Launch Formula using AI. Design the complete 4-phase launch structure: Pre-Prelaunch, PLC sequence, Launch, and Post-Launch. Embed 9 mental triggers — Authority, Reciprocity, Scarcity, Social Proof, and more — naturally into your content. AI generates the Sideways Sales Letter as a 3-part Prelaunch Content sequence, plus a complete 7-Day Launch Email Sequence from Cart Open to Final Close. Choose your launch type based on audience size: Seed (50-200), Internal (1K-5K), or JV (10K+).",
    sourceBook: "Product Launch Formula",
    sourceAuthor: "Jeff Walker",
    relatedBookSlug: "ai-startup-architect",
    keySteps: [
      "PLF 4-Phase Structure: Pre-Prelaunch, PLC sequence, Launch, Post-Launch",
      "Embed 9 Mental Triggers: Authority, Reciprocity, Scarcity, Social Proof",
      "Sideways Sales Letter: AI generates 3-part Prelaunch Content sequence",
      "7-Day Launch Email Sequence: every email from Cart Open to Final Close",
      "Choose launch type: Seed (50-200), Internal (1K-5K), JV (10K+)",
    ],
    useCases: [
      "Digital product creators planning their first launch",
      "Course creators automating recurring launches",
      "SaaS founders designing beta launch sequences",
    ],
  },
];

export const VALID_PATTERN_SLUGS = patterns.map((p) => p.slug);

export function getPatternBySlug(slug: string): Pattern | undefined {
  return patterns.find((p) => p.slug === slug);
}
